#!/bin/bash
# example file to be used with --hookdir
#
# 343894: a script to run debc command, contributed from q-funk.

apt-get install -y --force-yes devscripts
cd "$BUILDDIR"/*/debian
cd ..
debc
#EOF
