#!/bin/bash
# example file to be used with --hookdir
#
# run lintian on generated deb files
apt-get install -y -q --force-yes lintian
CHANGESFILE="$(find $BUILDDIR -maxdepth 1 -name '*.changes')"
LINTIANFILE="$CHANGESFILE.lintian"
lintian -i --allow-root --color always "$CHANGESFILE" | tee "$LINTIANFILE" || true
